language: python
python:
  - "2.6"
  - "2.7"
# install libhdf5 so pytables can link against it
# gdal required by fiona
before_install:
 - sudo add-apt-repository -y ppa:ubuntugis/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
 - sudo apt-get install -qq libhdf5-serial-dev
# commands to install ulmo
install: 
  - "pip install 'python-dateutil<2'"
  - "pip install numexpr"
  - "pip install cython"
  - "pip install tables"
  - "pip install fiona"
  - "pip install ."
  - "pip install sure"
  - "pip install freezegun"
  - "pip install pytest"
  - "pip install httpretty==0.8.6" #later versions cause IncompleteRead error
  - "pip install html5lib"

# command to run tests
script: "py.test"
