# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# Trun off email notifications
notifications:
  email: false

matrix:
  include:
    - os: osx
    - env: PYTHON_VERSION="2.7" OS_VERSION="MacOSX"

    - os: osx
    - env: PYTHON_VERSION="3.4" OS_VERSION="MacOSX"

    - os: linux
    - env: PYTHON_VERSION="2.7" OS_VERSION="Linux"

    - os: linux
    - env: PYTHON_VERSION="3.4" OS_VERSION="Linux"    

# commands to install ulmo
install: 
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-${OS_VERSION}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS_VERSION}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create ulmo venv and install deps
  - conda config --add channels ioos
  - conda create -q -n test-environment python=$PYTHON_VERSION appdirs beautifulsoup4 future geojson isodate lxml mock numpy pandas pytables pytest requests suds-jurko
  - source activate test-environment
  - pip install freezegun
  - pip install httpretty==0.8.6
  - python setup.py install

# command to run tests
script: "py.test"
