# conda environment file for python 2, includes packages needed for testing
# create a conda virtual env using:
#   conda env create -n myenv --file py2_conda_environment.yml
#   source activate myenv (use 'activate test_environment' on windows)
#   python setup.py develop
#
# optionally run tests:
#   python setup.py test

name: py2-ulmo

channels: 
    - ioos

dependencies:
    - python=2.7
    - appdirs
    - beautifulsoup4
    - future
    - geojson
    - isodate
    - lxml
    - mock
    - numpy
    - pandas
    - pytables
    - pytest
    - requests
    - suds-jurko
    - pip:
        - freezegun
        - httpretty==0.8.6
